// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjpzZqhVgTzaYtuHcA1o7HOeanLqPtV3k',
    appId: '1:431967022396:web:c53e5b52d4cbff3ab6c239',
    messagingSenderId: '431967022396',
    projectId: 'salon-app-207f7',
    authDomain: 'salon-app-207f7.firebaseapp.com',
    storageBucket: 'salon-app-207f7.firebasestorage.app',
    measurementId: 'G-L528Z4LDV5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCq6Pjk2F-h6Lu7wFRQwm0avvJ--DS8N24',
    appId: '1:431967022396:android:9e932400a81d146db6c239',
    messagingSenderId: '431967022396',
    projectId: 'salon-app-207f7',
    storageBucket: 'salon-app-207f7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOrLuXGum8OidCZM-jI9mV_FsODYFhwec',
    appId: '1:431967022396:ios:a93811f6b80e9842b6c239',
    messagingSenderId: '431967022396',
    projectId: 'salon-app-207f7',
    storageBucket: 'salon-app-207f7.firebasestorage.app',
    iosBundleId: 'com.example.salonappAppOwner',
  );
}
